"""Generate GRAPH_REPORT.md from analysis data."""
import json
from pathlib import Path


def generate_report(directory: str, meta: dict, quiet: bool = False):
    root = Path(directory).resolve()
    out_dir = root / 'astify-out'
    analysis_path = out_dir / 'analysis.json'

    # Load if not passed
    if meta is None:
        if analysis_path.exists():
            meta = json.loads(analysis_path.read_text(encoding='utf-8'))
        else:
            meta = {}

    lines = [
        '# ASTify Graph Report',
        '',
        f'**Nodes:** {meta.get("num_nodes", 0)}',
        f'**Edges:** {meta.get("num_edges", 0)}',
        f'**Analysis graph:** {meta.get("analysis_nodes", meta.get("num_nodes", 0))} nodes / '
        f'{meta.get("analysis_edges", meta.get("num_edges", 0))} edges',
        f'**Analysis mode:** {meta.get("analysis_mode", "legacy")}',
        f'**Communities:** {meta.get("num_communities", 0)}',
        f'**Tokens:** {meta.get("input_tokens", 0)} input / {meta.get("output_tokens", 0)} output',
        '',
        '---',
        '',
        '## Communities',
        '',
    ]

    labels = meta.get('labels', {})
    cohesion = meta.get('cohesion', {})
    communities = meta.get('communities', {})

    for cid in sorted(communities.keys(), key=lambda c: -len(communities[c])):
        members = communities[cid]
        label = labels.get(cid, f'Community {cid}')
        coh = cohesion.get(cid, 0)
        lines.append(f'### {label}')
        lines.append(f'*{len(members)} nodes · cohesion: {coh:.4f}*')
        lines.append('')
        for nid in members[:10]:
            lines.append(f'- `{nid}`')
        if len(members) > 10:
            lines.append(f'- ... and {len(members) - 10} more')
        lines.append('')

    lines.append('---')
    lines.append('')
    lines.append('## God Nodes')
    lines.append('')
    gods = meta.get('gods', [])
    for g in gods:
        lines.append(f'- **{g["label"]}** (degree: {g["degree"]}, '
                     f'community: {g["community"]})')
    if not gods:
        lines.append('*(none)*')
    lines.append('')

    lines.append('---')
    lines.append('')
    lines.append('## Surprising Connections')
    lines.append('')
    surprises = meta.get('surprises', [])
    for s in surprises:
        metric = s.get('metric', 'betweenness')
        lines.append(f'- **{s["source"]}** ↔ **{s["target"]}** '
                     f'({metric}: {s["betweenness"]})')
    if not surprises:
        lines.append('*(none)*')
    lines.append('')

    lines.append('---')
    lines.append('')
    lines.append('## Suggested Questions')
    lines.append('')
    questions = meta.get('questions', [])
    for q in questions:
        lines.append(f'- {q}')
    if not questions:
        lines.append('*(none)*')
    lines.append('')

    lines.append('---')
    lines.append('')
    lines.append('*Generated by ASTify — zero AI tokens*')
    lines.append('')

    report_path = out_dir / 'GRAPH_REPORT.md'
    report_path.write_text('\n'.join(lines), encoding='utf-8')

    if not quiet:
        print(f'Saved: {report_path}')

    return '\n'.join(lines)
